- name: Play1
  hosts: Test
  become: yes
  tasks:
   - name: Installing Docker on Slave
     shell: wget https://raw.githubusercontent.com/Vaibhav2406/edu-project1/main/Dockerinstall.sh -P /tmp
     shell: apt-get remove docker docker-engine docker.io containerd runc
     shell: apt-get update
     shell: apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
     shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | shell: apt-key add -
     shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
     shell: apt-get update
     shell: apt-get install -y docker-ce docker-ce-cli containerd.io
   - name: Updating repositories
     apt:
      update_cache: yes
   - name: checking Docker service
     shell: systemctl status docker
     register: consoleout
   - debug:
       var: consoleout.stdout_lines
