- name: Play1
  hosts: [Test]
  become: yes
  tasks:
   - name: Installing python target
     apt:
       update_cache: yes
       name: python3
       state: present
   - name: Checking Python Service
     shell: python3 --version
     register: consoleout
   - debug:
        var: consoleout.stdout_lines
   - name: Installing Git server
     apt:
       update_cache: yes
       name: software-properties-common
       state: present
   - name: Updating repositories
     shell: add-apt-repository ppa:git-core/ppa -y
   - name: Updating cache
     apt:
      update_cache: yes
      name: git
      state: present
   - name: Checking Git Version
     shell: git --version
     register: consoleout
   - debug:
        var: consoleout.stdout_lines
