- name: Play1
  hosts: Test
  become: yes
  tasks:
   - name: Installing Docker on Slave
     shell: wget https://raw.githubusercontent.com/Vaibhav2406/Website-Deploy-CICD/main/Docker-Installation/Dockerinstall.sh -P /tmp
     shell: chmod 755 /tmp/Dockerinstall.sh
     shell: bash /tmp/Dockerinstall.sh
   - name: Updating repositories
     apt:
      update_cache: yes
   - name: checking Docker service
     shell: systemctl status docker
     register: consoleout
   - debug:
       var: consoleout.stdout_lines
